// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PESYONG.Infrastructure;

#nullable disable

namespace PESYONG.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307090303_LastModifiedByOperatorIdNotRequired")]
    partial class LastModifiedByOperatorIdNotRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcknowledgementReceipt", b =>
                {
                    b.Property<int>("AcknowledgementReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcknowledgementReceiptID"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PromoID")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ShippingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AcknowledgementReceiptID");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CustomerID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.HasIndex("PromoID");

                    b.ToTable("AcknowledgementReceipts");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Audits.AuditLog", b =>
                {
                    b.Property<int>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogID"));

                    b.Property<int>("AuditActionType")
                        .HasColumnType("int");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AuditLogID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Financial.Payment", b =>
                {
                    b.Property<string>("PaymentID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("AcknowledgementRecieptID")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentID");

                    b.HasIndex("AcknowledgementRecieptID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Financial.Promos.Promo", b =>
                {
                    b.Property<int>("PromoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DiscountPercentageValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("PromoID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Promos");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Logistics.Delivery", b =>
                {
                    b.Property<int>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryID"));

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeliveryNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("DeliveryPersonnelID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLocationUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProofOfDelivery")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceivedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SignatureRequired")
                        .HasColumnType("bit");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeliveryID");

                    b.HasIndex("DeliveryPersonnelID");

                    b.HasIndex("OrderID");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Logistics.DeliveryUpdate", b =>
                {
                    b.Property<int>("DeliveryUpdateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryUpdateID"));

                    b.Property<int>("DeliveryID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("DeliveryUpdateID");

                    b.HasIndex("DeliveryID");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("DeliveryUpdates");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Meals.MealItem.Meal", b =>
                {
                    b.Property<int?>("MealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MealID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("LastModifiedByOperatorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MealPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MealTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinOrderQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("OperatorID")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("MealID");

                    b.HasIndex("OperatorID");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Meals.MealProduct.MealProduct", b =>
                {
                    b.Property<int>("MealProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealProductID"));

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PromoID")
                        .HasColumnType("int");

                    b.HasKey("MealProductID");

                    b.HasIndex("OwnerID");

                    b.HasIndex("PromoID");

                    b.ToTable("MealProduct");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReceiptID")
                        .HasColumnType("int");

                    b.Property<int?>("RecipientID")
                        .HasColumnType("int");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderID");

                    b.HasIndex("AppUserId");

                    b.HasIndex("RecipientID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Orders.OrderMealProduct", b =>
                {
                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MealProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MealProductOrderQty")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "MealProductID");

                    b.HasIndex("MealProductID");

                    b.ToTable("OrderMealProducts");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Users.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AuthorizationType")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("AcknowledgementReceipt", b =>
                {
                    b.HasOne("PESYONG.Domain.Entities.Users.Identity.AppUser", null)
                        .WithMany("UserReceipts")
                        .HasForeignKey("AppUserId");

                    b.HasOne("PESYONG.Domain.Entities.Users.Identity.AppUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PESYONG.Domain.Entities.Orders.Order", "Order")
                        .WithOne("Receipt")
                        .HasForeignKey("AcknowledgementReceipt", "OrderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PESYONG.Domain.Entities.Financial.Promos.Promo", "Promo")
                        .WithMany()
                        .HasForeignKey("PromoID");

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Promo");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Audits.AuditLog", b =>
                {
                    b.HasOne("PESYONG.Domain.Entities.Users.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Financial.Payment", b =>
                {
                    b.HasOne("AcknowledgementReceipt", "Receipt")
                        .WithMany()
                        .HasForeignKey("AcknowledgementRecieptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Logistics.Delivery", b =>
                {
                    b.HasOne("PESYONG.Domain.Entities.Users.Identity.AppUser", "DeliveryPersonnel")
                        .WithMany()
                        .HasForeignKey("DeliveryPersonnelID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PESYONG.Domain.Entities.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryPersonnel");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Logistics.DeliveryUpdate", b =>
                {
                    b.HasOne("PESYONG.Domain.Entities.Logistics.Delivery", "Delivery")
                        .WithMany("DeliveryUpdates")
                        .HasForeignKey("DeliveryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PESYONG.Domain.Entities.Users.Identity.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PESYONG.Domain.Entities.Users.Identity.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID");

                    b.Navigation("Delivery");

                    b.Navigation("UpdatedBy");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Meals.MealItem.Meal", b =>
                {
                    b.HasOne("PESYONG.Domain.Entities.Users.Identity.AppUser", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Meals.MealProduct.MealProduct", b =>
                {
                    b.HasOne("PESYONG.Domain.Entities.Users.Identity.AppUser", "Owner")
                        .WithMany("UserMealProducts")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PESYONG.Domain.Entities.Financial.Promos.Promo", "Promo")
                        .WithMany()
                        .HasForeignKey("PromoID");

                    b.OwnsMany("PESYONG.Domain.Entities.Meals.MealProduct.MealProductItem", "MealProductItems", b1 =>
                        {
                            b1.Property<int>("MealProductID")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("MealID")
                                .HasColumnType("int");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.Property<string>("RequestDescription")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("MealProductID", "Id");

                            b1.HasIndex("MealID");

                            b1.ToTable("MealProductItem");

                            b1.HasOne("PESYONG.Domain.Entities.Meals.MealItem.Meal", "Meal")
                                .WithMany()
                                .HasForeignKey("MealID")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("MealProductID");

                            b1.Navigation("Meal");
                        });

                    b.Navigation("MealProductItems");

                    b.Navigation("Owner");

                    b.Navigation("Promo");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Orders.Order", b =>
                {
                    b.HasOne("PESYONG.Domain.Entities.Users.Identity.AppUser", null)
                        .WithMany("UserOrders")
                        .HasForeignKey("AppUserId");

                    b.HasOne("PESYONG.Domain.Entities.Users.Identity.AppUser", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Orders.OrderMealProduct", b =>
                {
                    b.HasOne("PESYONG.Domain.Entities.Meals.MealProduct.MealProduct", "MealProduct")
                        .WithMany()
                        .HasForeignKey("MealProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PESYONG.Domain.Entities.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealProduct");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Logistics.Delivery", b =>
                {
                    b.Navigation("DeliveryUpdates");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("PESYONG.Domain.Entities.Users.Identity.AppUser", b =>
                {
                    b.Navigation("UserMealProducts");

                    b.Navigation("UserOrders");

                    b.Navigation("UserReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
