<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PESYONG.Infrastructure\PESYONG.Infrastructure.csproj" />
    <ProjectReference Include="..\PESYONG.Domain\PESYONG.Domain.csproj" />
    <ProjectReference Include="..\PESYONG.Application\PESYONG.ApplicationLogic.csproj" />
  </ItemGroup>

</Project>
