using PESYONG.Domain.Entities.Users.Identity;
using PESYONG.Domain.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PESYONG.Domain.Entities.Meals.MealItem;

/// <summary>
/// This is a meal generated by the operator.
/// </summary>

/// <remarks>
/// This needs further discussion on what to do with meal.
/// 2/20/26 MealTags are removed from Meal object.
/// 2/28/26 Image is now changed into byte[] blob
/// 2/28/26 Added OperatorID as main MealID user for this object.
/// </remarks>

public class Meal
{
    // Primary key
    [Key]
    public int MealID { get; set; }

    // This will be removed later on.
    public int RecipientID { get; set; }
    [ForeignKey(nameof(RecipientID))]
    private readonly AppUser? Recipient;

    // The recipientid will be replaced by OperatorID.
    public int OperatorID { get; set; }
    [ForeignKey(nameof(OperatorID))]
    private readonly AppUser? Operator;

    //removed mealtagjunction
    public ICollection<MealTag> MealTags { get; set; } = new List<MealTag>();

    // Attributes
    [Required(ErrorMessage = "Meal.MealName is required.")]
    [StringLength(100, ErrorMessage = "Meal.MealName must be less than 100 characters.")]
    public string MealName { get; set; } = string.Empty;

    [StringLength(500, ErrorMessage = "Meal.Description must be less than 500 characters.")]
    public string? Description { get; set; }

    [Required(ErrorMessage = "Meal.MealPrice is required.")]
    [Column(TypeName = "decimal(10,2)")]
    [Range(0.01, 1000000, ErrorMessage = "Meal.MealPrice must be greater than PHP0.01 and less than PHP1M.")]
    public decimal MealPrice { get; set; }

    //[Required(ErrorMessage = "Meal.ServingSizePAX is required.")]
    //[Column(TypeName = "decimal(6,2)")]
    //[Range(0.1, 1000, ErrorMessage = "Meal.ServingSizePAX must be between 0.1 and 1000.")]
    //public decimal ServingSizePAX { get; set; }

    [Required(ErrorMessage = "Meal.StockQuantity is required.")]
    [Range(0, int.MaxValue, ErrorMessage = "Meal.StockQuantity cannot be negative.")]
    public int StockQuantity { get; set; }

    [Required(ErrorMessage = "Meal.MinOrderQuantity is required.")]
    [Range(1, 1000, ErrorMessage = "Meal.MinOrderQuantity must be between 1 and 1000.")]
    public int MinOrderQuantity { get; set; } = 1;

    //[Required(ErrorMessage = "Meal.CaloriesPerServing is required.")]
    //[Range(0, 10000, ErrorMessage = "Meal.CaloriesPerServing must be between 0 and 10,000.")]
    //public int CaloriesPerServing { get; set; }

    //Delivery Type Enum
    [Required(ErrorMessage = "Delivery type is required.")]
    public DeliveryType DeliveryType { get; set; }




    // Server-side details ONLY
    // Timestamp and Audit
    [Required]
    public DateTime CreationDate { get; set; } = DateTime.UtcNow;

    // UpdatedBy -> Admin/Operator (mapping to AdminUser)
    [Required]
    public int LastModifiedByOperatorID { get; set; }

    [ForeignKey(nameof(LastModifiedByOperatorID))]
    public virtual AppUser? ModifiedByOperator { get; set; }

    [Required]
    public DateTime LastModifiedDate { get; set; } = DateTime.UtcNow;

    // Optional attributes (for now)
    // This needs more validation
    public byte[] BitmapImageBlob { get; set; }
}

