<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>preview</LangVersion>
		<RootNamespace>PESYONG.ApplicationLogic</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="InMemoryDb" Version="0.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PESYONG.Domain\PESYONG.Domain.csproj" />
		<ProjectReference Include="..\PESYONG.Infrastructure\PESYONG.Infrastructure.csproj" />
	</ItemGroup>
</Project>